import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppLayout from "@/AppLayout";
import QueryProviderWrapper from "@/wrappers/QueryProviderWrapper";
import { ToastContainer } from "react-toastify";
import AuthWrapper from "@/wrappers/AuthWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap"
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
      >
        <AuthWrapper>
          <QueryProviderWrapper>
            <AppLayout>
              {children}
            </AppLayout>
          </QueryProviderWrapper>
        </AuthWrapper>
        <ToastContainer
          position="top-right"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
      </body>
    </html>
  );
}

export default RootLayout
